---

name: Release to the Platform IO repository

on:
  release:
    types:
      - released
      - prereleased
      - edited

jobs:
  release_number:
    name: Release Number Validation
    runs-on: ubuntu-latest

    steps:
      ### Check the version number in the code matches the tag number
      - uses: actions/checkout@v4

      - name: Retrieve the version number(s)
        run: |
          TAG_VERSION=$(sed "s/^v//" <<< $GITHUB_REF_NAME)
          CODE_VERSION=$(jq ".version" library.json -r)
          echo TAG_VERSION=$TAG_VERSION >> $GITHUB_ENV
          echo CODE_VERSION=$CODE_VERSION >> $GITHUB_ENV
      - name: Check the version numberis semver compliant
        run: |
          if ! [[ $TAG_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-z]*[0-9]+)?$ ]]; then
            echo "ERROR: The version number is not semver compliant"
            exit 1
          fi
      - name: Check the version number in the code matches the tag number
        run: |
          if [ "$TAG_VERSION" != "$CODE_VERSION" ]; then
            echo "ERROR: The version number in the code ($CODE_VERSION) does not match the tag number ($TAG_VERSION)"
            exit 1
          fi

  release_to_platformio:
    name: Release to PlatformIO Registry
    runs-on: ubuntu-latest
    needs: release_number

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Platform IO
        run: |
          pip install -U platformio
          platformio update

      - name: Register new library version
        run: |
          PLATFORMIO_AUTH_TOKEN=${{ secrets.PLATFORMIO_AUTH_TOKEN }} pio pkg publish --type library --no-interactive --notify
