name: ESP-IDF v4.4.x

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build esp-idf v4.4.x examples

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/app

      - name: Set up Python
        uses: actions/setup-python@v4
  
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v4.4
          target: esp32
          path: app/examples/esp-idf