name: ESP-IDF v4.4.x

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:

  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["v4.4"]
        idf_target: ["esp32"]
        include:
          - idf_ver: "v4.4"
            idf_target: esp32s2
  
    runs-on: ubuntu-latest
    name: Build esp-idf v4.4.x examples

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/app

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
          path: app/examples/esp-idf
          command: apt-get update && apt-get install -y python3-venv && idf.py build