name: Platform IO

on:
  push:
    branches: []
  pull_request:
    branches: []
  schedule:
    - cron: "0 1 * * 6" # Every Saturday at 1AM  

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        feature: ["arduino2", "arduino2-ssl", "arduino2-regex", "arduino3", "arduino3-ssl", "arduino3-regex"]

    runs-on: ubuntu-latest
    name: Build ${{ matrix.feature }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Pythonf
        uses: actions/setup-python@v4

      - name: Install Platform IO
        run:
          |
          pip install -U platformio
          platformio update

      - name: Install Checked out PsychicHttp
        run:
          pio lib -g install $GITHUB_WORKSPACE

      - name: Build ${{ matrix.feature }} 
        run:
          |
          cd examples/platformio
          cp src/secret.h src/_secret.h
          pio run -e ${{ matrix.feature }}
